# Generated by Django 4.2.6 on 2023-11-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
