# Generated by Django 4.2.6 on 2023-11-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_alter_productimage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
